# stage2_panels.py
# ============================================================
# ORIGIN pipeline - STAGE 2: drywall panels, framing, soffits, columns, beams.
#
# Runs the five generators in origin_revit_drywall_scripts_v2_two_faces against a document
# handed in as an argument, so it works on a BACKGROUND document as well as the one open in
# the Revit UI. It differs from origin_bridge_run_all.py in exactly two ways, both required
# for background operation:
#
#   1. the target document is injected as ORIGIN_TARGET_DOC instead of each generator picking
#      up DocumentManager.Instance.CurrentDBDocument (the UI's document);
#   2. the elements to process are passed as IN[0] instead of through uidoc.Selection.
#      This is not a convenience - the Revit selection belongs to the ACTIVE document, and
#      feeding those element ids to a background document would silently resolve to whatever
#      unrelated elements happen to share those id numbers.
#
# Each generator opens and commits its own transaction (TransactionManager), so this module
# must NOT be called from inside one.
# ============================================================

import clr
import os
import re
import shutil
import time
import traceback

# Idempotent, and it keeps this module runnable on its own rather than only from a caller that
# happens to have loaded the assemblies already.
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')

from Autodesk.Revit.DB import *
from RevitServices.Transactions import TransactionManager

REPO = r"C:\Users\Origoncad\Downloads\origin_revit_drywall_scripts_v2_two_faces"
ROOT = r"C:\Users\Origoncad\origin_pipeline"

# Drive the ceiling generator's FURRING_RUN_NS from the site's main door instead of the
# hard-coded module constant, so one rule covers every env (see ceiling_direction.py). Set
# False to hand the generator back its own default.
CEILING_DIRECTION_FROM_DOOR = True

# Order matters: walls first (they own the corner/butt logic every other generator measures
# against), then ceilings, then the self-collecting plugins.
GENERATORS = [
    ("walls", "origin_wall_assembly_v4_phase2_notaper_noscrew_nojoint.py", "walls"),
    ("ceilings", "origin_ceiling_assembly_v1_notaper_noscrew_nojoint.py", "ceilings"),
    ("soffits", "origin_soffit_assembly_v1.py", "ceilings"),
    ("columns", "origin_column_assembly_v1.py", None),
    ("beams", "origin_beam_assembly_v1.py", None),
]

# Regenerated by every run, next to the generators. Copied into the per-env report folder so a
# batch does not leave only the last env's diagnostics behind.
MANIFESTS = [
    "origin_assembly_manifest_notaper_noscrew_nojoint.json",
    "origin_ceiling_manifest_notaper_noscrew_nojoint.json",
    "origin_soffit_manifest.json",
    "origin_column_manifest.json",
    "origin_beam_manifest.json",
]

SUMMARY_KEYS = ("warnings", "walls_skipped", "ceilings_skipped", "skipped", "notes")


def _slim(out):
    """Keep a generator's OUT small enough to travel through result.json: scalars plus the
    diagnostic lists. The full detail is in the manifests."""
    if not isinstance(out, dict):
        return {"OUT": str(out)}
    slim = {}
    for k, v in out.items():
        if isinstance(v, (int, float, str, bool)) or v is None:
            slim[k] = v
        elif k in SUMMARY_KEYS:
            slim[k] = v
    return slim


def collect_targets(doc):
    """Every wall and every ceiling in the document, as raw Revit elements. The generators run
    them through unwrap(), which is a no-op outside a Dynamo node, so raw elements are fine."""
    walls = list(FilteredElementCollector(doc).OfClass(Wall).WhereElementIsNotElementType())
    ceilings = list(FilteredElementCollector(doc).OfClass(Ceiling).WhereElementIsNotElementType())
    return {"walls": walls, "ceilings": ceilings}


def _apply_ceiling_direction(doc, src, report):
    """Set the ceiling generator's FURRING_RUN_NS from this site's main door.

    The repo file is never modified. The assignment is rewritten in the source STRING about to
    be compiled - the same mechanism run_drywall_on_ceilings.py already uses for layout
    overrides, and the reason the drywall repo can stay untouched while its behaviour is driven
    from here.

    If the direction cannot be resolved (an env whose doorways are bare gaps with no Door
    element, say) the source comes back unchanged and the generator's own default applies. That
    is a reported outcome, not a failure - a missing door must not stop the panels.
    """
    info = {"applied": False}
    try:
        ns = {"__name__": "ceiling_direction"}
        p = os.path.join(ROOT, "ceiling_direction.py")
        exec(compile(open(p).read(), p, "exec"), ns)

        res = ns["resolve_direction"](doc)
        # The full door list can be long; keep the decision and the runners-up, drop the rest.
        info["decision"] = dict((k, v) for k, v in res.items() if k != "doors")
        info["summary"] = ns["describe"](res)

        want = res.get("furring_run_ns")
        if want is None:
            info["skipped"] = res.get("reason")
            report["ceiling_direction"] = info
            return src

        pat = re.compile(r"^(FURRING_RUN_NS)\s*=\s*[^\n#]+", re.MULTILINE)
        m = pat.search(src)
        if m is None:
            info["skipped"] = "no FURRING_RUN_NS assignment found in the generator"
            report["ceiling_direction"] = info
            return src

        info["was"] = m.group(0).split("=", 1)[1].strip()
        info["now"] = str(want)
        src = pat.sub("FURRING_RUN_NS = " + str(want), src, count=1)
        info["applied"] = True
    except Exception:
        # Never let direction resolution take the panel run down with it.
        info["error"] = traceback.format_exc()[-800:]
    report["ceiling_direction"] = info
    return src


def run_on_document(doc, manifest_dir=None, only=None):
    """Run the generators against `doc`.

    manifest_dir - if given, each generator's manifest json is copied there afterwards.
    only         - optional list of generator labels, for narrowing a run while debugging.

    Returns a report dict; report["ok"] is True only if every generator ran without raising.
    """
    report = {"stage": "panels", "generators": {}, "ok": False}

    # The periodic bridge node may still be holding Dynamo's transaction against the UI
    # document. Leaving it open makes the first EnsureInTransaction here fail.
    try:
        TransactionManager.Instance.ForceCloseTransaction()
    except Exception:
        pass

    targets = collect_targets(doc)
    report["counts"] = {"walls": len(targets["walls"]), "ceilings": len(targets["ceilings"])}

    if not targets["walls"] and not targets["ceilings"]:
        report["error"] = "document contains no walls and no ceilings"
        return report

    fatal = False
    for (label, filename, kind) in GENERATORS:
        if only and label not in only:
            continue
        path = os.path.join(REPO, filename)
        t0 = time.time()
        if not os.path.exists(path):
            report["generators"][label] = {"FATAL": "generator not found: {}".format(path)}
            fatal = True
            continue

        ns = {
            "IN": [None] * 10,
            "OUT": None,
            "__name__": "__main__",
            "__file__": path,
            # picked up by the patched `doc = ...` line at the top of each generator
            "ORIGIN_TARGET_DOC": doc,
        }
        if kind:
            ns["IN"][0] = targets[kind]

        try:
            src = open(path).read()
            if label == "ceilings" and CEILING_DIRECTION_FROM_DOOR:
                src = _apply_ceiling_direction(doc, src, report)
            exec(compile(src, path, "exec"), ns)
            entry = _slim(ns.get("OUT"))
        except Exception:
            entry = {"FATAL": traceback.format_exc()}
            fatal = True
            # Do not leave a half-open transaction behind for the next generator.
            try:
                TransactionManager.Instance.ForceCloseTransaction()
            except Exception:
                pass
        entry["sec"] = round(time.time() - t0, 2)
        report["generators"][label] = entry

    # The generators end with TransactionTaskDone(), but under Dynamo's automatic transaction
    # strategy that only hands the transaction back - it stays open until the graph goes idle,
    # which never happens inside a bridge command. The document then refuses to save with
    # "Unable to close all open transaction phases!". ForceCloseTransaction commits it here,
    # so the caller gets a document that is actually ready to be written.
    try:
        TransactionManager.Instance.ForceCloseTransaction()
        report["transaction_force_closed"] = True
    except Exception:
        report["transaction_force_closed"] = traceback.format_exc()

    if manifest_dir:
        copied = []
        for m in MANIFESTS:
            src = os.path.join(REPO, m)
            if os.path.exists(src):
                try:
                    shutil.copy2(src, os.path.join(manifest_dir, m))
                    copied.append(m)
                except Exception:
                    pass
        report["manifests_copied"] = copied

    report["ok"] = not fatal
    return report
