# origin_bridge_revert_unapproved_walls.py - run via the ORIGIN Bridge.
# Deletes every ST-*/DP-* DirectShape generated by the wall script EXCEPT those tagged to a wall
# in KEEP_EIDS - reverting the two unauthorized full-model runs back to only the walls the user
# explicitly reviewed and approved one at a time. DRY_RUN=True reports counts without deleting;
# set to False (and re-run) to actually delete.
import clr

clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager

uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
target_title = uidoc.Document.Title
doc = uidoc.Document
for d in app.Documents:
    if d.Title == target_title:
        doc = d
        break

KEEP_EIDS = {403281, 400324, 401552, 395748, 380854, 392686, 407836, 391807, 410850, 411863}
KEEP_TAGS = set("WALL=W" + str(e) for e in KEEP_EIDS)
APP_ID = "ORIGIN_ASSEMBLY_V4"
DRY_RUN = True

to_delete = []
kept = []
untagged = []
for ds in FilteredElementCollector(doc).OfClass(DirectShape).ToElements():
    try:
        cm = ds.get_Parameter(BuiltInParameter.ALL_MODEL_INSTANCE_COMMENTS)
        comments = cm.AsString() if cm else None
    except Exception:
        comments = None
    if not comments or not comments.startswith(APP_ID + " |"):
        continue
    host = None
    for tok in comments.split("|"):
        tok = tok.strip()
        if tok.startswith("WALL="):
            host = tok
    try:
        mk = ds.get_Parameter(BuiltInParameter.ALL_MODEL_MARK)
        mark = mk.AsString() if mk else None
    except Exception:
        mark = None
    if host is None:
        untagged.append(mark)
        continue
    if host in KEEP_TAGS:
        kept.append(mark)
    else:
        to_delete.append((ds, mark, host))

deleted = 0
if not DRY_RUN:
    for (ds, mark, host) in to_delete:
        try:
            doc.Delete(ds.Id)
            deleted += 1
        except Exception:
            continue

OUT = {
    "dry_run": DRY_RUN,
    "keep_eids": sorted(KEEP_EIDS),
    "kept_count": len(kept),
    "to_delete_count": len(to_delete),
    "deleted_count": deleted,
    "untagged_count": len(untagged),
    "sample_to_delete": [{"mark": m, "host": h} for (_, m, h) in to_delete[:20]],
}
